# Generated by Django 5.0.6 on 2026-06-09 21:21

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="file_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="document",
            name="ingestion_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="ingestion_status",
            field=models.CharField(
                choices=[("completed", "Completed")], default="completed", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="source_file",
            field=models.FileField(
                blank=True, null=True, upload_to=documents.models.document_upload_path
            ),
        ),
    ]
