# Generated by Django 5.1.15 on 2026-06-23 10:01

from django.db import migrations, models


def set_existing_source_kind(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Document.objects.filter(source_type="upload").update(source_kind="upload")
    Document.objects.exclude(source_type="upload").update(source_kind="manual")


def reset_existing_source_kind(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Document.objects.all().update(source_kind="manual")


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_file_size_document_file_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="fetch_provider",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="document",
            name="fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="http_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="source_domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="source_kind",
            field=models.CharField(
                choices=[("manual", "Manual"), ("upload", "Upload"), ("url", "URL")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.RunPython(set_existing_source_kind, reset_existing_source_kind),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_kind", "url"), models.Q(("source_url", ""), _negated=True)
                ),
                fields=("source_url",),
                name="unique_url_document_source_url",
            ),
        ),
    ]
